version: '3.8'



services:

  sleek-airflow:

    image: mlops-airflow:latest

    

    volumes:

      - ./airflow:/opt/airflow



    ports:

      - "8080:8080"



    command: airflow standalone
    
    deploy:
      resources:
        limits:
          memory: 1.5g
          cpus: 2
    